#include <pebble.h>
#include "pdc-transform.h"

/* =========================================================
   CONFIGURATION
   -------------------------------------------------------
   Edit these constants to customise watchface behaviour.
========================================================= */

// Defaults — overwritten at runtime from persistent storage / AppMessage.
// Change these to set the out-of-box experience before a user opens the
// phone config page.
static bool     config_24h           = false; // true = 24 h, false = 12 h
static bool     config_anim_enabled  = true;  // smooth sweep vs tick-per-second
static uint32_t config_anim_duration = 900;   // ms per sweep (100–1000)
// Seconds to show the sunsecond before hiding it; 0 = always visible.
// app_focus_service fires for notifications but NOT for the Pebble's
// backlight/idle timeout, so we use a countdown timer instead.
static uint32_t config_timeout_s     = 10;

// Persistent storage keys (arbitrary, must not collide with other keys)
#define PERSIST_KEY_24H           0
#define PERSIST_KEY_ANIM_ENABLED  1
#define PERSIST_KEY_ANIM_DURATION 2
#define PERSIST_KEY_TIMEOUT_S     3

// Generated by the build system from package.json messageKeys
extern uint32_t MESSAGE_KEY_KEY_24H;
extern uint32_t MESSAGE_KEY_KEY_ANIM_ENABLED;
extern uint32_t MESSAGE_KEY_KEY_ANIM_DURATION;
extern uint32_t MESSAGE_KEY_KEY_TIMEOUT_S;

/* =========================================================
   GLOBAL MOVEMENT SYSTEM
========================================================= */

static int MOVE_ALL_X = 0;
static int MOVE_ALL_Y = 0;

static int HEARTS_X = 0;
static int HEARTS_Y = 0;

static int HOUR_X = 20;
static int HOUR_Y = -32;

static int MINUTE_X = 13;
static int MINUTE_Y = -53;

static int DATE_X = 3;
static int DATE_Y = 10;

static int GREEN_X = 60;
static int GREEN_Y = 11;

static int BLUE_X = 93;
static int BLUE_Y = 27;

static int LEFTC_X  = 95;
static int LEFTC_Y  = 0;

static int RIGHTC_X = 125;
static int RIGHTC_Y = 0;

static int DOWNC_X  = 112;
static int DOWNC_Y  = 15;

static int ARCH_X   = 0;
static int ARCH_Y   = 95;

/* Desired rendered size of the arch in pixels (width = height).
   Change this variable to resize the arch at runtime.
   100 = native PDC size. 150 = 1.5× native size, etc.            */
static int ARCH_SCALE = 150;

static int SPEED_X      = 44;
static int SPEED_Y      = 130;


static int WALLET_X     = 0;
static int WALLET_Y     = 35;

static int MAGIC_X      = 0;
static int MAGIC_Y      = 28;

static int STEPS_X      = 10;
static int STEPS_Y      = 35;

/* =========================================================
   WINDOW
========================================================= */

static Window *s_window;

/* =========================================================
   OUTLINED TEXT LAYERS
========================================================= */

typedef struct {
  const char    *text;
  GFont          font;
  GColor         fg;
  GColor         outline;
  GTextAlignment align;
} OLTextState;

static void ol_text_update_proc(Layer *layer, GContext *ctx) {
  OLTextState *s = (OLTextState *)layer_get_data(layer);
  if (!s->text || s->text[0] == '\0') return;
  GRect b = layer_get_bounds(layer);
  const int8_t dx[] = {-1, 1,  0, 0};
  const int8_t dy[] = { 0, 0, -1, 1};
  graphics_context_set_text_color(ctx, s->outline);
  for (int i = 0; i < 4; i++) {
    GRect ob = GRect(b.origin.x + dx[i], b.origin.y + dy[i], b.size.w, b.size.h);
    graphics_draw_text(ctx, s->text, s->font, ob, GTextOverflowModeWordWrap, s->align, NULL);
  }
  graphics_context_set_text_color(ctx, s->fg);
  graphics_draw_text(ctx, s->text, s->font, b, GTextOverflowModeWordWrap, s->align, NULL);
}

static Layer *s_hour_layer;
static Layer *s_minute_layer;
static Layer *s_date_layer;
static Layer *s_day_layer;

static char hour_buffer[3];
static char minute_buffer[3];
static char date_buffer[16];
static char day_buffer[16];

/* =========================================================
   HEARTS
========================================================= */

static BitmapLayer *s_hearts[10];

/* C BUTTONS */
static BitmapLayer *s_leftc_layer;
static BitmapLayer *s_rightc_layer;
static BitmapLayer *s_downc_layer;

static GBitmap *s_leftc_bmp;
static GBitmap *s_rightc_bmp;
static GBitmap *s_downc_bmp;

/* ICONS */
static BitmapLayer *s_speed_layer;
static BitmapLayer *s_sun_moon_layer;
static BitmapLayer *s_sun_second_layer;
static BitmapLayer *s_wallet_layer;
static BitmapLayer *s_magic_layer;

static AppTimer  *s_anim_timer     = NULL;
static int        s_anim_start_sec = 0;
static int        s_anim_fire_count = 0;
static bool       s_in_focus       = true;
static AppTimer  *s_timeout_timer  = NULL;

static GBitmap *s_speed_bmp;
static GBitmap *s_hour_sun_bmp;
static GBitmap *s_moon_hour_bmp;
static GBitmap *s_sun_second_bmp;
static GBitmap *s_wallet_bmp;
static GBitmap *s_magic_bmp;

/* STEP DIGITS */
static GBitmap *s_digit_bmps[10];
#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
static BitmapLayer *s_steps_digits[10];
static int          s_steps_digit_count = 0;
#endif

#if defined(PBL_HEALTH)
static Layer *s_hr_layer;
static char   s_hr_buffer[8];
#endif

/* =========================================================
   FONTS
========================================================= */

static GFont s_tri_font_28;
static GFont s_tri_font_18;
static GFont s_tri_font_14;

/* ARCH (vector PDC) */
static Layer              *s_arch_layer;
static GDrawCommandImage  *s_arch_cmd;

/* =========================================================
   MAIN UI
========================================================= */

static BitmapLayer *s_green_circle;
static BitmapLayer *s_blue_circle;

/* =========================================================
   BITMAPS
========================================================= */

static GBitmap *s_green_bmp;
static GBitmap *s_blue_bmp;

static GBitmap *s_heart_full_bmp;
static GBitmap *s_heart_3quarter_bmp;
static GBitmap *s_heart_half_bmp;
static GBitmap *s_heart_quarter_bmp;
static GBitmap *s_heart_empty_bmp;

/* =========================================================
   RECT HELPER
========================================================= */

static GRect rect_pos(int x, int y, int w, int h) {
  return GRect(
    x + MOVE_ALL_X,
    y + MOVE_ALL_Y,
    w,
    h);
}

/* =========================================================
   LOAD RESOURCES
========================================================= */

static void load_resources(void) {

  s_green_bmp =
      gbitmap_create_with_resource(RESOURCE_ID_IMAGE_GREEN);
  s_blue_bmp =
      gbitmap_create_with_resource(RESOURCE_ID_IMAGE_BLUE);
  s_heart_full_bmp =
      gbitmap_create_with_resource(RESOURCE_ID_HEART_FULL);
  s_heart_3quarter_bmp =
      gbitmap_create_with_resource(RESOURCE_ID_HEART_3QUARTER);
  s_heart_half_bmp =
      gbitmap_create_with_resource(RESOURCE_ID_HEART_HALF);
  s_heart_quarter_bmp =
      gbitmap_create_with_resource(RESOURCE_ID_HEART_QUARTER);
  s_heart_empty_bmp =
      gbitmap_create_with_resource(RESOURCE_ID_HEART_EMPTY);
  s_leftc_bmp  = gbitmap_create_with_resource(RESOURCE_ID_LEFTC);
  s_rightc_bmp = gbitmap_create_with_resource(RESOURCE_ID_RIGHTC);
  s_downc_bmp  = gbitmap_create_with_resource(RESOURCE_ID_CDOWN);
  s_speed_bmp      = gbitmap_create_with_resource(RESOURCE_ID_SPEED);
  s_hour_sun_bmp   = gbitmap_create_with_resource(RESOURCE_ID_HOUR_SUN);
  s_moon_hour_bmp  = gbitmap_create_with_resource(RESOURCE_ID_MOON_HOUR);
  s_sun_second_bmp = gbitmap_create_with_resource(RESOURCE_ID_SUN_SECOND);
  s_wallet_bmp     = gbitmap_create_with_resource(RESOURCE_ID_WALLET_ICON);
  s_magic_bmp      = gbitmap_create_with_resource(RESOURCE_ID_MAGIC_BAR);

#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
  s_digit_bmps[0] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_0);
  s_digit_bmps[1] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_1);
  s_digit_bmps[2] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_2);
  s_digit_bmps[3] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_3);
  s_digit_bmps[4] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_4);
  s_digit_bmps[5] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_5);
  s_digit_bmps[6] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_6);
  s_digit_bmps[7] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_7);
  s_digit_bmps[8] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_8);
  s_digit_bmps[9] = gbitmap_create_with_resource(RESOURCE_ID_DIGIT_9);
#endif

#if !defined(PBL_PLATFORM_APLITE)
  s_arch_cmd =
      gdraw_command_image_create_with_resource(RESOURCE_ID_ARCH);
#endif

  s_tri_font_28 = fonts_load_custom_font(resource_get_handle(RESOURCE_ID_TRI_FONT_28));
#if !defined(PBL_PLATFORM_APLITE)
  s_tri_font_18 = fonts_load_custom_font(resource_get_handle(RESOURCE_ID_TRI_FONT_18));
  s_tri_font_14 = fonts_load_custom_font(resource_get_handle(RESOURCE_ID_TRI_FONT_14));
#else
  s_tri_font_18 = fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD);
  s_tri_font_14 = fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD);
#endif
}

/* =========================================================
   UNLOAD RESOURCES
========================================================= */

static void unload_resources(void) {

  gbitmap_destroy(s_green_bmp);
  gbitmap_destroy(s_blue_bmp);

  gbitmap_destroy(s_heart_full_bmp);
  gbitmap_destroy(s_heart_3quarter_bmp);
  gbitmap_destroy(s_heart_half_bmp);
  gbitmap_destroy(s_heart_quarter_bmp);
  gbitmap_destroy(s_heart_empty_bmp);

  gbitmap_destroy(s_leftc_bmp);
  gbitmap_destroy(s_rightc_bmp);
  gbitmap_destroy(s_downc_bmp);

  gbitmap_destroy(s_speed_bmp);
  gbitmap_destroy(s_hour_sun_bmp);
  gbitmap_destroy(s_moon_hour_bmp);
  gbitmap_destroy(s_sun_second_bmp);
  gbitmap_destroy(s_wallet_bmp);
  gbitmap_destroy(s_magic_bmp);

#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
  for (int i = 0; i < 10; i++) {
    gbitmap_destroy(s_digit_bmps[i]);
  }
#endif

#if !defined(PBL_PLATFORM_APLITE)
  if (s_arch_cmd) {
    gdraw_command_image_destroy(s_arch_cmd);
    s_arch_cmd = NULL;
  }
#endif

  fonts_unload_custom_font(s_tri_font_28);
#if !defined(PBL_PLATFORM_APLITE)
  fonts_unload_custom_font(s_tri_font_18);
  fonts_unload_custom_font(s_tri_font_14);
#endif
}

/* =========================================================
   ARCH DRAW
   -------------------------------------------------------
   pdc_transform_gdraw_command_image_draw_transformed()
   derives scale10 from ARCH_SCALE vs. the PDC's native
   bounding-box width so the arch renders at exactly
   ARCH_SCALE × ARCH_SCALE pixels regardless of what size
   the original .pdc was authored at.

   It makes an internal copy of s_arch_cmd each frame, so
   the master image is never mutated.
========================================================= */

// GPoints from timespan.svg, all scaled ×3 (ARCH_SCALE=150 / SVG width=50).
// path1_3 = main arch body (outer + inner arc as one closed polygon).
// path2–12 = radial spoke marks; drawn BLACK on the white arch body so they
//            are visible (in color they are white on a colored background).
// path52–63 = hour-marker ovals (2–4 px); drawn as small black squares.
#if defined(PBL_PLATFORM_APLITE)
static const GPoint s_arch_body[] = {
  {142,71},{143,71},{144,71},{145,71},{146,71},{147,71},{147,70},{148,70},
  {149,69},{150,68},{104,74},{108,73},{113,73},{120,73},
  {126,72},{132,72},{136,72},{138,72},{138,71},{138,70},{138,68},{138,67},
  {138,66},{137,64},{137,63},{137,61},{137,60},{136,60},{136,59},{136,57},
  {135,56},{134,54},{134,53},{133,51},{132,50},{132,49},{131,48},{130,47},
  {130,46},{129,46},{129,45},{128,44},{127,43},{126,42},{125,41},{124,39},
  {122,38},{121,37},{121,36},{120,36},{119,35},{118,34},{117,34},{116,33},
  {115,32},{113,31},{112,30},{110,29},{108,28},{107,28},{106,27},{105,27},
  {103,26},{102,26},{101,25},{99,25},{98,24},{96,24},{95,23},{93,23},
  {92,23},{91,23},{91,22},{90,22},{89,22},{88,22},{87,22},{86,22},
  {84,22},{83,22},{82,22},{80,22},{79,22},{77,22},{76,22},{75,22},
  {74,22},{73,22},{72,22},{71,22},{69,22},{68,22},{67,22},{65,22},
  {64,22},{63,22},{62,22},{61,22},{60,22},{60,23},{59,23},{57,23},
  {55,24},{53,24},{52,25},{50,25},{49,26},{47,26},{46,27},{45,27},
  {44,28},{43,28},{42,29},{40,29},{39,30},{37,31},{36,32},{35,33},
  {33,33},{32,35},{31,35},{31,36},{30,36},{29,37},{28,38},{27,39},
  {26,40},{24,41},{23,43},{22,44},{21,46},{20,47},{20,48},{19,48},
  {19,50},{18,51},{17,52},{17,53},{16,55},{16,56},{15,57},{15,59},
  {14,59},{14,60},{14,61},{14,62},{14,63},{14,64},{13,65},{13,66},
  {13,67},{13,68},{13,69},{13,70},{13,71},{0,69},
  {4,72},{5,72},{6,72},{7,72},{7,71},{8,71},{8,70},{8,69},
  {8,68},{8,67},{8,66},{8,65},{9,64},{9,63},{9,62},{9,61},
  {9,59},{10,58},{10,57},{10,55},{11,54},{11,53},{12,51},{13,50},
  {13,49},{14,47},{15,46},{16,45},{16,44},{17,43},{18,42},{18,41},
  {19,40},{21,39},{22,37},{24,36},{26,34},{28,32},{32,29},{36,27},
  {40,25},{43,23},{47,22},{50,20},{53,20},{56,19},{55,18},{55,17},
  {55,16},{56,15},{56,14},{57,13},{58,13},{59,12},{60,12},{62,12},
  {63,12},{65,12},{66,12},{67,13},{68,13},{69,13},{68,13},{67,12},
  {66,11},{66,10},{65,9},{66,9},{66,8},{67,8},{68,9},{69,9},
  {70,10},{70,11},{71,11},{71,12},{71,11},{71,10},{70,10},{70,9},
  {70,8},{70,7},{69,7},{69,6},{69,5},{70,4},{70,3},{71,2},
  {71,1},{72,1},{74,0},{75,0},{76,0},{77,1},{78,1},{79,2},
  {80,3},{81,4},{81,5},{81,6},{81,7},{81,8},{81,9},{80,10},
  {80,11},{79,11},{80,11},{80,10},{81,10},{81,9},{82,9},{82,8},
  {83,8},{84,8},{85,8},{85,9},{85,10},{84,10},{84,11},{83,12},
  {82,13},{83,13},{83,12},{84,12},{85,12},{86,12},{87,11},{88,11},
  {89,11},{90,11},{91,12},{92,12},{93,13},{94,14},{94,15},{94,16},
  {95,16},{95,17},{95,18},{94,18},{94,19},{95,20},{96,20},{97,20},
  {98,20},{99,21},{100,21},{102,21},{107,23},{111,25},{115,27},{119,29},
  {122,31},{124,33},{126,34},{127,35},{128,37},{130,39},{131,41},{133,43},
  {136,47},{137,50},{139,54},{141,59},{141,61},{142,62},{142,64},{142,66},
  {142,67},{142,69},{142,70},{142,71},
};
static const GPoint s_sp2[] = {
  {105,27},{106,27},{107,28},{108,28},{107,29},{106,30},{104,33},{101,37},
  {97,42},{94,47},{91,51},{89,54},{88,55},{88,54},{90,51},{93,46},
  {96,41},{99,36},{102,31},{104,28},{105,27},
};
static const GPoint s_sp3[] = {
  {61,22},{62,22},{63,22},{68,52},{59,24},{59,23},{60,23},{60,22},{61,22},
};
static const GPoint s_sp4[] = {
  {92,23},{82,50},{88,22},{89,22},{90,22},{91,22},{91,23},{92,23},
};
static const GPoint s_sp5[] = {
  {136,60},{137,60},{137,61},{98,68},{136,59},{136,60},
};
static const GPoint s_sp6[] = {
  {131,48},{96,64},{94,65},{129,46},{130,46},{130,47},{131,48},
};
static const GPoint s_sp7[] = {
  {121,37},{91,60},{93,59},{96,56},{100,52},{105,47},{110,43},{115,39},
  {118,36},{119,35},{120,36},{121,36},{121,37},
};
static const GPoint s_sp8[] = {
  {77,22},{75,48},{74,22},{75,22},{76,22},{77,22},
};
static const GPoint s_sp9[] = {
  {46,27},{64,57},{43,28},{44,28},{45,27},{46,27},
};
static const GPoint s_sp10[] = {
  {60,61},{59,60},{30,36},{31,36},{31,35},{32,35},{60,61},
};
static const GPoint s_sp11[] = {
  {55,64},{19,48},{20,48},{20,47},{21,46},{55,64},
};
static const GPoint s_sp12[] = {
  {53,69},{14,61},{14,60},{14,59},{15,59},{53,69},
};
// Crown decorations: oval bobble, spike, right wing, left wing (ts_path1_0/1/2/4)
static const GPoint s_crown0[] = {
  {73,19},{74,19},{74,20},{75,20},{76,20},{76,19},{77,19},{77,18},
  {76,18},{75,18},{74,18},{73,19},
};
static const GPoint s_crown1[] = {
  {73,3},{73,4},{73,5},{73,6},{73,7},{73,8},{73,9},{73,10},
  {74,10},{74,11},{74,12},{75,12},{76,12},{76,11},{76,10},{77,10},
  {77,9},{77,8},{77,7},{77,6},{77,5},{77,4},{77,3},{76,3},
  {75,3},{75,2},{75,3},{74,3},{73,3},
};
static const GPoint s_crown2[] = {
  {91,16},{91,15},{90,15},{88,14},{86,15},{84,15},{83,15},{81,16},
  {80,16},{80,17},{81,17},{82,17},{83,17},{84,17},{85,17},{86,18},
  {87,18},{88,18},{89,18},{90,18},{91,18},{91,17},{92,17},{92,16},
  {91,16},
};
static const GPoint s_crown4[] = {
  {70,16},{69,16},{67,15},{66,15},{64,15},{62,15},{61,15},{60,15},
  {59,16},{59,17},{59,18},{60,18},{61,18},{62,18},{63,18},{63,17},
  {64,17},{66,17},{67,17},{68,17},{69,17},{70,17},{70,16},
};
// Hour-marker centres (path52–63, 11 unique positions)
static const GPoint s_markers[] = {
  {14,60},{20,47},{31,36},{45,28},{61,22},{76,22},
  {91,22},{107,28},{121,36},{131,47},{137,60},
};
static void prv_fill_path(GContext *ctx, const GPoint *pts, uint16_t n) {
  GPathInfo info = { .num_points = n, .points = (GPoint*)pts };
  GPath *p = gpath_create(&info);
  if (p) { gpath_draw_filled(ctx, p); gpath_destroy(p); }
}
#endif

static void arch_update_proc(Layer *layer, GContext *ctx) {
#if defined(PBL_PLATFORM_APLITE)
  // Everything is drawn white. The arch band is white on black background.
  // The spokes extend from the inner arc downward into the black interior —
  // they are visible as white shapes against the black background, exactly
  // as the SVG renders them on colour platforms.
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_context_set_stroke_color(ctx, GColorWhite);

  // 1. Arch body + crown decorations
  prv_fill_path(ctx, s_arch_body, ARRAY_LENGTH(s_arch_body));
  prv_fill_path(ctx, s_crown0,    ARRAY_LENGTH(s_crown0));
  prv_fill_path(ctx, s_crown1,    ARRAY_LENGTH(s_crown1));
  prv_fill_path(ctx, s_crown2,    ARRAY_LENGTH(s_crown2));
  prv_fill_path(ctx, s_crown4,    ARRAY_LENGTH(s_crown4));

  // 2. Radial spokes — white fill, visible in the black interior
  prv_fill_path(ctx, s_sp2,  ARRAY_LENGTH(s_sp2));
  prv_fill_path(ctx, s_sp3,  ARRAY_LENGTH(s_sp3));
  prv_fill_path(ctx, s_sp4,  ARRAY_LENGTH(s_sp4));
  prv_fill_path(ctx, s_sp5,  ARRAY_LENGTH(s_sp5));
  prv_fill_path(ctx, s_sp6,  ARRAY_LENGTH(s_sp6));
  prv_fill_path(ctx, s_sp7,  ARRAY_LENGTH(s_sp7));
  prv_fill_path(ctx, s_sp8,  ARRAY_LENGTH(s_sp8));
  prv_fill_path(ctx, s_sp9,  ARRAY_LENGTH(s_sp9));
  prv_fill_path(ctx, s_sp10, ARRAY_LENGTH(s_sp10));
  prv_fill_path(ctx, s_sp11, ARRAY_LENGTH(s_sp11));
  prv_fill_path(ctx, s_sp12, ARRAY_LENGTH(s_sp12));

  // 3. Hour marker ovals — white, visible against the black interior
  for (int k = 0; k < (int)ARRAY_LENGTH(s_markers); k++) {
    graphics_fill_rect(ctx,
      GRect(s_markers[k].x - 1, s_markers[k].y - 1, 3, 3),
      0, GCornerNone);
  }
#else
  if (!s_arch_cmd) return;
  GSize native = gdraw_command_image_get_bounds_size(s_arch_cmd);
  int scale10 = (native.w > 0)
    ? (ARCH_SCALE * 10) / native.w
    : 10;
  pdc_transform_gdraw_command_image_draw_transformed(
    ctx,
    s_arch_cmd,
    GPoint(0, 0),
    scale10,
    0,
    GColorClear,
    GColorClear,
    0
  );
#endif
}

/* =========================================================
   HEART LOOKUP
========================================================= */

static GBitmap *heart_bitmap(int level) {

  switch (level) {
    case 4:  return s_heart_full_bmp;
    case 3:  return s_heart_3quarter_bmp;
    case 2:  return s_heart_half_bmp;
    case 1:  return s_heart_quarter_bmp;
    default: return s_heart_empty_bmp;
  }
}

/* =========================================================
   UPDATE HEARTS FROM BATTERY
========================================================= */

static void update_hearts(int battery_percent) {
  /*
     Battery expressed as 40 quarter-subunits (10 hearts × 4 levels).
     Fill order: indices 0..4 = top row left→right,
                          5..9 = bottom row left→right.

     Remainder mapping (how many quarter-subunits are in the partial heart):
       remainder 3 → quarterheart  (level 1)
       remainder 2 → halfheart     (level 2)
       remainder 1 → 3quarterheart (level 3)
       remainder 0 → empty         (level 0)
  */

  int total_subunits = (battery_percent * 40) / 100;
  int full_hearts    = total_subunits / 4;
  int remainder      = total_subunits % 4;

  for (int i = 0; i < 10; i++) {

    if (i < full_hearts) {

      bitmap_layer_set_bitmap(s_hearts[i], heart_bitmap(4));

    } else if (i == full_hearts) {

      int level;
      switch (remainder) {
        case 3:  level = 1; break;
        case 2:  level = 2; break;
        case 1:  level = 3; break;
        default: level = 0; break;
      }
      bitmap_layer_set_bitmap(s_hearts[i], heart_bitmap(level));

    } else {
      bitmap_layer_set_bitmap(s_hearts[i], heart_bitmap(0));
    }
  }
}

/* =========================================================
   BATTERY CALLBACK
========================================================= */

static void battery_callback(BatteryChargeState state) {
  update_hearts(state.charge_percent);
}

/* =========================================================
   UPDATE TIME
========================================================= */

static void arch_ellipse_pos(int angle_deg, int *out_x, int *out_y) {
  GRect bounds = layer_get_bounds(window_get_root_layer(s_window));
  int center_x = ARCH_X + ARCH_SCALE / 2;
  int center_y = bounds.size.h - MOVE_ALL_Y;
  int radius_x = (ARCH_SCALE * 45) / 100;
  int radius_y = ((bounds.size.h - 2 * MOVE_ALL_Y - ARCH_Y) * 10) / 13;

  int32_t angle = DEG_TO_TRIGANGLE(angle_deg);
  *out_x = center_x + (radius_x * cos_lookup(angle)) / TRIG_MAX_RATIO;
  *out_y = center_y - (radius_y * sin_lookup(angle)) / TRIG_MAX_RATIO;
}

static void update_sun_moon(int hour_24, int minute) {
  bool is_day = (hour_24 >= 6 && hour_24 < 18);
  int angle_deg;

  if (is_day) {
    // Sun: left (180°) at 6am → crown (90°) at noon → right (0°) at 6pm
    int mins = (hour_24 - 6) * 60 + minute;
    angle_deg = 180 - mins / 4;
  } else {
    // Moon: left (180°) at 6pm → crown (90°) at midnight → right (0°) at 6am
    int mins = (hour_24 >= 18) ? (hour_24 - 18) * 60 + minute
                                : (hour_24 + 6) * 60 + minute;
    angle_deg = 180 - mins / 4;
  }

  int x, y;
  arch_ellipse_pos(angle_deg, &x, &y);

  int icon_w = 18;
  int icon_h = is_day ? 18 : 20;
  bitmap_layer_set_bitmap(s_sun_moon_layer, is_day ? s_hour_sun_bmp : s_moon_hour_bmp);
  layer_set_frame(bitmap_layer_get_layer(s_sun_moon_layer),
                  rect_pos(x - icon_w / 2, y - icon_h / 2, icon_w, icon_h));
}

// Positions the sunsecond icon at the given trig-domain angle.
// Radii are 80% of the main arc (tighter ellipse).
// angle uses the same 0x0000–0xFFFF scale as cos_lookup / sin_lookup per
// https://developer.repebble.com/docs/c/Foundation/Math/
// (TRIG_MAX_RATIO = 0xFFFF is the max return value; TRIG_MAX_ANGLE = 0x10000
// represents a full 360° rotation.)
static void update_sun_second(int32_t angle) {
  GRect bounds = layer_get_bounds(window_get_root_layer(s_window));
  int center_x = ARCH_X + ARCH_SCALE / 2;
  int center_y = bounds.size.h - MOVE_ALL_Y;
  int radius_x = (ARCH_SCALE * 45 * 8) / 1000;
  int radius_y = ((bounds.size.h - 2 * MOVE_ALL_Y - ARCH_Y) * 80) / 130;

  int x = center_x + (radius_x * cos_lookup(angle)) / TRIG_MAX_RATIO;
  int y = center_y - (radius_y * sin_lookup(angle)) / TRIG_MAX_RATIO;

  layer_set_frame(bitmap_layer_get_layer(s_sun_second_layer),
                  rect_pos(x - 8, y - 8, 16, 16));
}

static void update_time(void) {

  time_t       temp      = time(NULL);
  struct tm   *tick_time = localtime(&temp);

  int hour = tick_time->tm_hour;

  if (!config_24h) {
    hour = hour % 12;
    if (hour == 0) hour = 12;
  }

  snprintf(hour_buffer,   sizeof(hour_buffer),   "%d",    hour);
  snprintf(minute_buffer, sizeof(minute_buffer),  "%02d",  tick_time->tm_min);

  snprintf(date_buffer,   sizeof(date_buffer),
           "%d/%d",
           tick_time->tm_mday,
           tick_time->tm_mon + 1);

  const char *days[] = {
    "SUN","MON","TUE","WED","THU","FRI","SAT"
  };
  const char *months[] = {
    "JAN","FEB","MAR","APR","MAY","JUN",
    "JUL","AUG","SEP","OCT","NOV","DEC"
  };

  snprintf(day_buffer, sizeof(day_buffer),
           "%s %s",
           days[tick_time->tm_wday],
           months[tick_time->tm_mon]);

  layer_mark_dirty(s_hour_layer);
  layer_mark_dirty(s_minute_layer);
  layer_mark_dirty(s_date_layer);
  layer_mark_dirty(s_day_layer);

  update_sun_moon(tick_time->tm_hour, tick_time->tm_min);
}

/* =========================================================
   SUN-SECOND ANIMATION
   -------------------------------------------------------
   AppTimer-based sweep: fires every ANIM_INTERVAL_MS and
   interpolates the angle linearly.  AppTimers fire in both
   bright and dim display modes, so behaviour is consistent
   regardless of the backlight state.
========================================================= */

#define ANIM_INTERVAL_MS 33u  /* ~30 fps */

static void anim_timer_cb(void *context) {
  s_anim_timer = NULL;
  s_anim_fire_count++;
  uint32_t elapsed = s_anim_fire_count * ANIM_INTERVAL_MS;

  int32_t start_a = DEG_TO_TRIGANGLE(180 - s_anim_start_sec * 3);
  int32_t end_a   = DEG_TO_TRIGANGLE(180 - (s_anim_start_sec + 1) * 3);

  if (elapsed >= config_anim_duration) {
    update_sun_second(end_a);
    return;
  }

  int32_t angle = start_a + (int32_t)((int64_t)(end_a - start_a)
                             * elapsed / config_anim_duration);
  update_sun_second(angle);
  s_anim_timer = app_timer_register(ANIM_INTERVAL_MS, anim_timer_cb, NULL);
}

static void start_sec_animation(int second) {
  if (!s_in_focus) return;

  if (s_anim_timer) {
    app_timer_cancel(s_anim_timer);
    s_anim_timer = NULL;
  }

  s_anim_start_sec = second;
  s_anim_fire_count = 0;
  update_sun_second(DEG_TO_TRIGANGLE(180 - second * 3));

  if (!config_anim_enabled || config_anim_duration == 0) return;

  s_anim_timer = app_timer_register(ANIM_INTERVAL_MS, anim_timer_cb, NULL);
}

/* =========================================================
   TICK
========================================================= */

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  // Always refresh hours/minutes — calling on every second is cheap because
  // TextLayer only triggers a redraw when the string content actually changes.
  // Relying solely on MINUTE_UNIT misses stale-time cases on some Rebble builds.
  update_time();
  start_sec_animation(tick_time->tm_sec);
}

/* =========================================================
   SUNSECOND VISIBILITY TIMER
   -------------------------------------------------------
   app_focus_service fires for notifications but NOT when
   the Pebble backlight simply times out from inactivity.
   A countdown timer is the only reliable cross-firmware
   way to hide the icon after a configurable idle period.
========================================================= */

static void hide_sun_second(void) {
  s_in_focus = false;
  if (s_anim_timer) {
    app_timer_cancel(s_anim_timer);
    s_anim_timer = NULL;
  }
  layer_set_hidden(bitmap_layer_get_layer(s_sun_second_layer), true);
}

static void timeout_cb(void *context) {
  s_timeout_timer = NULL;
  hide_sun_second();
}

// Call whenever the sunsecond should (re)appear and the countdown should reset.
static void show_sun_second(void) {
  if (s_timeout_timer) {
    app_timer_cancel(s_timeout_timer);
    s_timeout_timer = NULL;
  }
  s_in_focus = true;
  layer_set_hidden(bitmap_layer_get_layer(s_sun_second_layer), false);
  if (config_timeout_s > 0) {
    s_timeout_timer = app_timer_register(config_timeout_s * 1000,
                                         timeout_cb, NULL);
  }
}

static void focus_handler(bool in_focus) {
  if (in_focus) {
    // Notification dismissed / system UI gone — reset the countdown.
    show_sun_second();
    update_time();
    time_t now = time(NULL);
    struct tm *t = localtime(&now);
    start_sec_animation(t->tm_sec);
  } else {
    // Notification / system UI covering the watchface — hide immediately.
    hide_sun_second();
    if (s_timeout_timer) {
      app_timer_cancel(s_timeout_timer);
      s_timeout_timer = NULL;
    }
  }
}

/* =========================================================
   HEART RATE
========================================================= */

#if defined(PBL_HEALTH)
static void update_heart_rate(void) {
  HealthServiceAccessibilityMask mask = health_service_metric_accessible(
      HealthMetricHeartRateBPM, time(NULL) - 30, time(NULL));
  if (mask & HealthServiceAccessibilityMaskAvailable) {
    HealthValue hr = health_service_peek_current_value(HealthMetricHeartRateBPM);
    snprintf(s_hr_buffer, sizeof(s_hr_buffer), "%d", (int)hr);
  } else {
    snprintf(s_hr_buffer, sizeof(s_hr_buffer), "--");
  }
  layer_mark_dirty(s_hr_layer);
}
#endif

#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
static void update_steps(void) {
  for (int i = 0; i < s_steps_digit_count; i++) {
    bitmap_layer_destroy(s_steps_digits[i]);
    s_steps_digits[i] = NULL;
  }
  s_steps_digit_count = 0;

  HealthValue steps = health_service_sum_today(HealthMetricStepCount);
  int s = (int)steps;

  int num_digits = 1;
  int temp = s;
  while (temp >= 10) { temp /= 10; num_digits++; }

  int divisors[10] = {1000000000, 100000000, 10000000, 1000000, 100000, 10000, 1000, 100, 10, 1};
  int start = 10 - num_digits;

  Layer *window_layer = window_get_root_layer(s_window);
  for (int i = 0; i < num_digits; i++) {
    int digit = (s / divisors[start + i]) % 10;
    s_steps_digits[i] = bitmap_layer_create(
        rect_pos(STEPS_X + (i * 11), STEPS_Y, 10, 14));
    bitmap_layer_set_bitmap(s_steps_digits[i], s_digit_bmps[digit]);
    bitmap_layer_set_compositing_mode(s_steps_digits[i], GCompOpSet);
    layer_add_child(window_layer, bitmap_layer_get_layer(s_steps_digits[i]));
  }
  s_steps_digit_count = num_digits;
}

static void health_handler(HealthEventType event, void *context) {
#if defined(PBL_HEALTH)
  if (event == HealthEventHeartRateUpdate || event == HealthEventSignificantUpdate) {
    update_heart_rate();
  }
#endif
  if (event == HealthEventMovementUpdate || event == HealthEventSignificantUpdate) {
    update_steps();
  }
}
#endif

/* =========================================================
   WINDOW LOAD
========================================================= */

static void window_load(Window *window) {

  Layer *window_layer = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(window_layer);

  // Center the 144×168 design on any screen (emery=200×228, chalk=180×180, etc.)
  MOVE_ALL_X = (bounds.size.w - 144) / 2;
  MOVE_ALL_Y = (bounds.size.h - 168) / 2;

  // On round displays push hearts inward so they clear the curved corners
  HEARTS_X = PBL_IF_RECT_ELSE(0, 22);
  HEARTS_Y = PBL_IF_RECT_ELSE(0, 20);

  load_resources();

  /* -------------------------------------------------------
     BACKGROUND
  ------------------------------------------------------- */

  window_set_background_color(window, GColorBlack);

  /* -------------------------------------------------------
     HEARTS — two rows of 5
  ------------------------------------------------------- */

  for (int i = 0; i < 5; i++) {
    s_hearts[i] = bitmap_layer_create(
        rect_pos(HEARTS_X + (i * 14), HEARTS_Y, 12, 10));
    bitmap_layer_set_compositing_mode(s_hearts[i], GCompOpSet);
    layer_add_child(window_layer, bitmap_layer_get_layer(s_hearts[i]));
  }

  for (int i = 0; i < 5; i++) {
    s_hearts[i + 5] = bitmap_layer_create(
        rect_pos(HEARTS_X + (i * 14), HEARTS_Y + 14, 12, 10));
    bitmap_layer_set_compositing_mode(s_hearts[i + 5], GCompOpSet);
    layer_add_child(window_layer, bitmap_layer_get_layer(s_hearts[i + 5]));
  }

  /* -------------------------------------------------------
     GREEN + BLUE CIRCLES
  ------------------------------------------------------- */

  s_blue_circle = bitmap_layer_create(
      rect_pos(BLUE_X, BLUE_Y, 54, 54));
  bitmap_layer_set_bitmap(s_blue_circle, s_blue_bmp);
  bitmap_layer_set_compositing_mode(s_blue_circle, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_blue_circle));

  s_green_circle = bitmap_layer_create(
      rect_pos(GREEN_X, GREEN_Y, 54, 54));
  bitmap_layer_set_bitmap(s_green_circle, s_green_bmp);
  bitmap_layer_set_compositing_mode(s_green_circle, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_green_circle));

  /* -------------------------------------------------------
     C BUTTONS
  ------------------------------------------------------- */

  s_leftc_layer = bitmap_layer_create(
      rect_pos(LEFTC_X, LEFTC_Y, 20, 20));
  bitmap_layer_set_bitmap(s_leftc_layer, s_leftc_bmp);
  bitmap_layer_set_compositing_mode(s_leftc_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_leftc_layer));

  s_rightc_layer = bitmap_layer_create(
      rect_pos(RIGHTC_X, RIGHTC_Y, 20, 20));
  bitmap_layer_set_bitmap(s_rightc_layer, s_rightc_bmp);
  bitmap_layer_set_compositing_mode(s_rightc_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_rightc_layer));

  s_downc_layer = bitmap_layer_create(
      rect_pos(DOWNC_X, DOWNC_Y, 20, 20));
  bitmap_layer_set_bitmap(s_downc_layer, s_downc_bmp);
  bitmap_layer_set_compositing_mode(s_downc_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_downc_layer));

  /* -------------------------------------------------------
     ICONS
  ------------------------------------------------------- */

  s_speed_layer = bitmap_layer_create(rect_pos(SPEED_X, SPEED_Y, 60, 51));
  bitmap_layer_set_bitmap(s_speed_layer, s_speed_bmp);
  bitmap_layer_set_compositing_mode(s_speed_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_speed_layer));

  s_magic_layer = bitmap_layer_create(rect_pos(MAGIC_X, MAGIC_Y, 50, 6));
  bitmap_layer_set_bitmap(s_magic_layer, s_magic_bmp);
  bitmap_layer_set_compositing_mode(s_magic_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_magic_layer));

  s_wallet_layer = bitmap_layer_create(rect_pos(WALLET_X, WALLET_Y, 12, 15));
  bitmap_layer_set_bitmap(s_wallet_layer, s_wallet_bmp);
  bitmap_layer_set_compositing_mode(s_wallet_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_wallet_layer));


  /* -------------------------------------------------------
     ARCH — vector PDC layer
  ------------------------------------------------------- */

  s_arch_layer = layer_create(
      rect_pos(ARCH_X, ARCH_Y, ARCH_SCALE, ARCH_SCALE));
  layer_set_update_proc(s_arch_layer, arch_update_proc);
  layer_add_child(window_layer, s_arch_layer);

  /* sun/moon and sun-second must be added AFTER arch so they draw on top */
  s_sun_moon_layer = bitmap_layer_create(GRect(0, 0, 18, 20));
  bitmap_layer_set_compositing_mode(s_sun_moon_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_sun_moon_layer));

  s_sun_second_layer = bitmap_layer_create(GRect(0, 0, 16, 16));
  bitmap_layer_set_bitmap(s_sun_second_layer, s_sun_second_bmp);
  bitmap_layer_set_compositing_mode(s_sun_second_layer, GCompOpSet);
  layer_add_child(window_layer, bitmap_layer_get_layer(s_sun_second_layer));

  /* -------------------------------------------------------
     TEXT LAYERS — added last so they render on top of everything
  ------------------------------------------------------- */

  #define MAKE_OL_LAYER(var, x, y, w, h, buf, fnt, al) do { \
    (var) = layer_create_with_data(rect_pos((x),(y),(w),(h)), sizeof(OLTextState)); \
    OLTextState *_s = (OLTextState *)layer_get_data(var); \
    _s->text    = (buf); \
    _s->font    = (fnt); \
    _s->fg      = PBL_IF_COLOR_ELSE(GColorYellow, GColorWhite); \
    _s->outline = GColorBlack; \
    _s->align   = (al); \
    layer_set_update_proc((var), ol_text_update_proc); \
    layer_add_child(window_layer, (var)); \
  } while (0)

  MAKE_OL_LAYER(s_hour_layer,   40+HOUR_X,   48+HOUR_Y,   54, 42, hour_buffer,   s_tri_font_28, GTextAlignmentCenter);
  MAKE_OL_LAYER(s_minute_layer, 80+MINUTE_X, 86+MINUTE_Y, 54, 42, minute_buffer, s_tri_font_28, GTextAlignmentCenter);
  MAKE_OL_LAYER(s_date_layer,   DATE_X+32,   DATE_Y+120,  80, 24, date_buffer,   s_tri_font_18, GTextAlignmentCenter);
  MAKE_OL_LAYER(s_day_layer,    DATE_X+24,   DATE_Y+142,  96, 24, day_buffer,    s_tri_font_14, GTextAlignmentCenter);

  #undef MAKE_OL_LAYER

#if defined(PBL_HEALTH)
  s_hr_layer = layer_create_with_data(rect_pos(LEFTC_X, LEFTC_Y, 20, 20), sizeof(OLTextState));
  { OLTextState *_s = (OLTextState *)layer_get_data(s_hr_layer);
    _s->text    = s_hr_buffer;
    _s->font    = s_tri_font_14;
    _s->fg      = PBL_IF_COLOR_ELSE(GColorYellow, GColorWhite);
    _s->outline = GColorBlack;
    _s->align   = GTextAlignmentCenter; }
  snprintf(s_hr_buffer, sizeof(s_hr_buffer), "--");
  layer_set_update_proc(s_hr_layer, ol_text_update_proc);
  layer_add_child(window_layer, s_hr_layer);
#endif

  /* -------------------------------------------------------
     INITIAL DRAW
  ------------------------------------------------------- */

  BatteryChargeState charge = battery_state_service_peek();
  update_hearts(charge.charge_percent);

  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  update_time();
  show_sun_second();          // starts visibility countdown
  start_sec_animation(t->tm_sec);

#if defined(PBL_HEALTH)
  update_heart_rate();
#endif
#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
  update_steps();
#endif
}

/* =========================================================
   WINDOW UNLOAD
========================================================= */

static void window_unload(Window *window) {

  if (s_timeout_timer) {
    app_timer_cancel(s_timeout_timer);
    s_timeout_timer = NULL;
  }
  if (s_anim_timer) {
    app_timer_cancel(s_anim_timer);
    s_anim_timer = NULL;
  }

  layer_destroy(s_hour_layer);
  layer_destroy(s_minute_layer);
  layer_destroy(s_date_layer);
  layer_destroy(s_day_layer);
#if defined(PBL_HEALTH)
  layer_destroy(s_hr_layer);
#endif

  bitmap_layer_destroy(s_green_circle);
  bitmap_layer_destroy(s_blue_circle);

  for (int i = 0; i < 10; i++) {
    bitmap_layer_destroy(s_hearts[i]);
  }

  bitmap_layer_destroy(s_leftc_layer);
  bitmap_layer_destroy(s_rightc_layer);
  bitmap_layer_destroy(s_downc_layer);

  bitmap_layer_destroy(s_speed_layer);
  bitmap_layer_destroy(s_magic_layer);
  bitmap_layer_destroy(s_sun_moon_layer);
  bitmap_layer_destroy(s_sun_second_layer);
  bitmap_layer_destroy(s_wallet_layer);

#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
  for (int i = 0; i < s_steps_digit_count; i++) {
    bitmap_layer_destroy(s_steps_digits[i]);
  }
#endif

  layer_destroy(s_arch_layer);

  unload_resources();
}

/* =========================================================
   SETTINGS — persistent storage + AppMessage
========================================================= */

static void load_settings(void) {
  if (persist_exists(PERSIST_KEY_24H))
    config_24h = persist_read_bool(PERSIST_KEY_24H);
  if (persist_exists(PERSIST_KEY_ANIM_ENABLED))
    config_anim_enabled = persist_read_bool(PERSIST_KEY_ANIM_ENABLED);
  if (persist_exists(PERSIST_KEY_ANIM_DURATION))
    config_anim_duration = (uint32_t)persist_read_int(PERSIST_KEY_ANIM_DURATION);
  if (persist_exists(PERSIST_KEY_TIMEOUT_S))
    config_timeout_s = (uint32_t)persist_read_int(PERSIST_KEY_TIMEOUT_S);
}

static void inbox_received_handler(DictionaryIterator *iter, void *context) {
  Tuple *t;

  t = dict_find(iter, MESSAGE_KEY_KEY_24H);
  if (t) {
    config_24h = (bool)t->value->int32;
    persist_write_bool(PERSIST_KEY_24H, config_24h);
  }

  t = dict_find(iter, MESSAGE_KEY_KEY_ANIM_ENABLED);
  if (t) {
    config_anim_enabled = (bool)t->value->int32;
    persist_write_bool(PERSIST_KEY_ANIM_ENABLED, config_anim_enabled);
  }

  t = dict_find(iter, MESSAGE_KEY_KEY_ANIM_DURATION);
  if (t) {
    config_anim_duration = (uint32_t)t->value->int32;
    persist_write_int(PERSIST_KEY_ANIM_DURATION, (int32_t)config_anim_duration);
  }

  t = dict_find(iter, MESSAGE_KEY_KEY_TIMEOUT_S);
  if (t) {
    config_timeout_s = (uint32_t)t->value->int32;
    persist_write_int(PERSIST_KEY_TIMEOUT_S, (int32_t)config_timeout_s);
  }

  // Refresh display with new settings.
  update_time();
  time_t now = time(NULL);
  struct tm *t2 = localtime(&now);
  start_sec_animation(t2->tm_sec);
}

/* =========================================================
   INIT
========================================================= */

static void init(void) {

  load_settings();

  s_window = window_create();

  window_set_window_handlers(s_window, (WindowHandlers) {
    .load   = window_load,
    .unload = window_unload,
  });

  window_stack_push(s_window, true);

  tick_timer_service_subscribe(SECOND_UNIT, tick_handler);
  battery_state_service_subscribe(battery_callback);
  app_focus_service_subscribe(focus_handler);
#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
  health_service_events_subscribe(health_handler, NULL);
#endif

  app_message_register_inbox_received(inbox_received_handler);
  app_message_open(128, 128);
}

/* =========================================================
   DEINIT
========================================================= */

static void deinit(void) {

  tick_timer_service_unsubscribe();
  battery_state_service_unsubscribe();
  app_focus_service_unsubscribe();
#if defined(PBL_HEALTH) || defined(PBL_PLATFORM_APLITE)
  health_service_events_unsubscribe();
#endif
  window_destroy(s_window);
}

/* =========================================================
   MAIN
========================================================= */

int main(void) {
  init();
  app_event_loop();
  deinit();
}
